### ISSUE TITLE
Implementação do readme.md

### ISSUE THREAD

**Issue by viniciusDias1001** [portal-ciclismo/APi-Ciclismo#6]

**Comment by Matheuxnr** [comment]
<h1>Rede-Social-Ciclismo</h1>

> Status: Em Desenvolvimento ⚠️

### Um site dedicado a todos os entusiastas do ciclismo, sejam eles ciclistas de estrada, mountain bikers, urbanos ou amantes das pedaladas elétricas.

## Recursos Principais:

+ Análises de Bicicletas 
+ Trilhas e Rotas 
+ Manutenção de Bicicletas 
+ Dicas de Treinamento e Desempenho
+ Guias de Compra de Bicicletas 

## Dados do Usuario:

+ Nome
+ Email
+ Cpf
+ Aniversario

## Ferramentas utilizadas:

+ Node.Js
+ Npm
+ react-router-dom
+ axios
+ jwt-decode
+ react-bootstrap
+ Java Jre 8
+ Java JDK 17
+ MySql 8.0.21
+ Maven

## Editores de Código utilizados:

+ VsCode
+ Intellij IDE
