### ISSUE TITLE
Criação do controller de Perfil

### ISSUE THREAD

**Issue by ryanjorgeac** [portal-ciclismo/APi-Ciclismo#80]
Por que essa issue é necessária?
- Para exibição de endpoint e métodos HTTP de Perfil 

Em caso de bug, descreva como reproduzi-lo. Em caso de melhoria, direcione a solução informando possíveis tecnologias ou por onde seguir:
- Consuma o service de perfil (ex.: perfilService)
- Atenção para requestMapping
- Informe a URL que o controller vai ser responsável após /api
- Lembrar do encapsulamento
- Lidar com Optionals da maneira correta
- Utilizar DTO do Perfil

Informações adicionais:

**Comment by glpontes** [comment]
Profile refatorado por outra pessoa e controller criado, issue não mais necessária
